# Allocate smaller chunks of memory per pod.
elasticsearchHosts: "http://elasticsearch-master:9200"
resources:
  requests:
    cpu: "100m"
    memory: "800M"
  limits:
    cpu: "1000m"
    memory: "800M"
